name: Build & Publish (win-x64)

# Запускаем вручную и при пуше в main и при создании тега v*
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build-publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Publish self-contained single-file (win-x64)
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true -o ./publish/win-x64

      - name: Prepare release folder
        run: |
          mkdir release || true
          cp -r publish/win-x64/* release/ || true
          # include config sample (if exists) and README
          if [ -f config.sample.json ]; then cp config.sample.json release/config.sample.json; fi
          cp README.md release/ || true

      - name: Zip release
        run: |
          powershell -Command "Compress-Archive -Path release/* -DestinationPath release/dayz-fishing-bot-win-x64.zip -Force"

      - name: Upload artifact (Actions)
        uses: actions/upload-artifact@v4
        with:
          name: dayz-fishing-bot-win-x64
          path: release/dayz-fishing-bot-win-x64.zip

      - name: Create GitHub Release (on tag push)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release/dayz-fishing-bot-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}